apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: {{ .Values.adservice.replicaCount }}
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: {{ .Values.adservice.image.repository }}:{{ .Values.adservice.image.tag }}
        imagePullPolicy: Always

        env:
        - name: PORT
          value: "9555"

        - name: DISABLE_PROFILER
          value: "1"

        - name: ENABLE_TRACING
          value: "0"

        ports:
        - containerPort: 9555
