apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fast

spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  storageClassName: fast-storage

  hostPath:
    path: /data/fast