apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-slow

spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  storageClassName: slow-storage

  hostPath:
    path: /data/slow