apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: special-pvc

spec:
  volumeName: special-pv

  storageClassName: ""

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 500Mi